initial setup
shiftforward-io/shiftforward-io pull request #1
Opened 2024-06-03 08:12 UTC by nabilwinfo

initial setup for the project with html template.

2024-06-03 16:18 UTC, chiragpaliwal requested changes

2024-06-03 16:18 UTC, chiragpaliwal commented on .gitignore
> +docs/
I don't see a docs directory, why is this added?

2024-06-03 16:18 UTC, chiragpaliwal commented on pnpm-lock.yaml
Do we need to commit this file?

2024-06-03 16:18 UTC, chiragpaliwal commented on src/_data/about.json
> +  "para1": "At ShiftForward, we specialize in delivering high-impact solutions with Microsoft Dynamics 365, Salesforce, Shopify, and custom web applications. Our mission is to empower businesses by p
Can we use better naming convetions like subheading, subtitle, applies to both `para1` and `para2`

2024-06-03 16:18 UTC, chiragpaliwal commented on src/_data/contact.json
> +  "email": "you@domain.com",
hi@winfotech.co

2024-06-03 16:18 UTC, chiragpaliwal commented on src/_data/contact.json
> +  "address": "12345 Porto Blvd.\nSuite 1500.\nLos Angeles, California 90000",
1 Shiv Colony, North Sunderwas, Udaipur, 313001

2024-06-03 16:18 UTC, chiragpaliwal commented on src/_data/services.json
For all the icon images, did we get the actual icons for Microsoft, Salesforce, Shopify etc?

2024-06-04 05:20 UTC, nabilwinfotech commented on pnpm-lock.yaml
Yes. Because this helps to prevent the "works on my machine" problem, as everyone will have the same dependencies with the same versions. It records the exact version of each dependency, including transitive dependencies (i.e., dependencies of dependencies). This provides a consistent and reliable way to manage dependencies.

2024-06-04 05:20 UTC, nabilwinfotech commented on .gitignore
> +docs/
sure, let me remove!

2024-06-04 05:42 UTC, nabilwinfotech commented on src/_data/about.json
> +  "para1": "At ShiftForward, we specialize in delivering high-impact solutions with Microsoft Dynamics 365, Salesforce, Shopify, and custom web applications. Our mission is to empower businesses by p
sure!

2024-06-04 07:38 UTC, nabilwinfo commented on src/_data/services.json
done

2024-06-12 11:52 UTC, chiragpaliwal approved these changes

2024-06-12 11:52 UTC, merged